name: baserouter
description: A layered routing package and general mini-state carrier for flutter apps.
version: 0.0.2
homepage: https://github.com/onuohasilver/flexible_router

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
